Montages-Team/MontageClient

- README.md
- src/package-lock.json
> 環境構築時のエラー修正

- src/src/components/molecules/CategoryLabels.vue
- src/src/components/molecules/ProfileCardStats.vue
- src/src/components/molecules/TopMenu.vue
> fix nits vue warning

- src/src/components/atoms/followButton.vue
- src/src/components/molecules/ProfileCardStats.vue
- src/src/components/molecules/ProfileImageTop.vue
>  [fix] プロフィール画像のオーバフローエリアのデザイン修正

- src/src/components/atoms/ConfirmButton.vue
- src/src/components/molecules/ProfilePageMenu.vue
- src/src/components/molecules/QuestionCard.vue
- src/src/components/molecules/ReactionIconGroup.vue
- src/src/components/organisms/Impressions.vue
- src/src/components/organisms/ModalForm.vue
- src/src/components/organisms/Questions.vue
#79 
* Collage機能の追加
* メニューが切り替わらないバグの修正
* lengthのエラーを修正
> 79 collage button modal

- src/package-lock.json
- src/src/App.vue
- src/src/components/organisms/Questions.vue
> ハードコードと不要なリンクを削除

- src/src/components/organisms/Questions.vue
> [fix] refs #100 スクロールイベントを検知後のQuestionを取得処理発火の条件を修正

- src/src/App.vue
- src/src/components/organisms/Header.vue
* https://github.com/Montages-Team/MontageClient/issues/78
- `style` のスタイルは書きやすさ読みやすさがそれぞれあると思うので、違う意見があればください
> ヘッダーにメニューを追加 

- src/src/App.vue
- src/src/components/organisms/Header.vue
- src/src/components/organisms/HeaderMenu.vue
> ヘッダメニューを追加

- src/src/App.vue
- src/src/components/molecules/ProfileImageTop.vue
- src/src/components/molecules/QuestionCard.vue
- src/src/components/organisms/AccountSettings.vue
- src/src/components/organisms/DeactivateForm.vue
- src/src/components/organisms/HeaderMenu.vue
- src/src/router.ts
> 設定画面の不具合修正

- src/src/App.vue
- src/src/components/organisms/Header.vue
- src/src/components/organisms/Loading.vue
- src/src/components/organisms/Terms.vue
- src/src/components/pages/Profile.vue
- src/src/views/Callback.vue
> [Add] ローディング画面の追加

- src/src/components/organisms/AccountSettings.vue
- src/src/components/organisms/DeactivateForm.vue
- src/src/components/organisms/Footer.vue
- src/src/components/pages/About.vue
- src/src/components/pages/Faq.vue
- src/src/components/pages/Profile.vue
- src/src/constants/delete_user_query.ts
- src/src/router.ts
#119 #121 
[fix] Footerのデザインを修正
[fix] ユーザー登録処理のリファクタリング
[Add] 退会処理の実装
[Add] ヘルプページとサイト紹介ページの追加
> フッター修正＆退会処理の実装&ヘルプページとサイト紹介ページの実装

- .gitignore
- src/.gitignore
- src/package-lock.json
- src/package.json
- src/server.js
※ distディレクトリにbuildされてherokuで使われるのでgitignoreから削除しておく必要がある。
> [Add] Herokuデプロイ用の修正

- src/package-lock.json
- src/package.json
- src/public/index.html
- src/src/App.vue
- src/src/components/atoms/ProfileRoundImage.vue
- src/src/components/molecules/ProfileImageTop.vue
- src/src/components/molecules/QuestionCard.vue
- src/src/components/organisms/Footer.vue
- src/src/components/organisms/Header.vue
- src/src/main.ts
[fix] 画像の遅延ロードを行うように修正
[Add] cssのプリロードの追加
[fix] フッターのリンクでログイン時にホーム画面に飛ばないように修正
[fix] ヘッダーのリロード時の挙動の修正
> パフォーマンス修正&ヘッダー/フッターの挙動の修正

- src/src/auth/authService.ts
- src/src/components/molecules/QuestionCard.vue
- src/src/components/organisms/AccountSettings.vue
- src/src/components/organisms/DeactivateForm.vue
- src/src/components/organisms/Footer.vue
- src/src/components/organisms/Header.vue
- src/src/components/organisms/HeaderMenu.vue
- src/src/components/pages/Home.vue
- src/src/components/pages/NotFound.vue
- src/src/components/pages/Profile.vue
- src/src/router.ts
- src/src/views/Callback.vue
#116 の追加
- [fix] ログインボタンの近くに利用規約とプライバシーポリシーへのリンクを配置
- [add] NotFoundページの追加
- [fix] import文を整形
- [fix] 未ログインのアクセス許可
- [fix] ログイン時、未ログイン時のルーティング処理を最適化
下記シートに全てのテストケース書いた。それぞれためしてほしい
https://docs.google.com/spreadsheets/d/1qUb8Ao6_tDnn-p4jM35IbD6nA8yP1IualKsjrOBYcrk/edit#gid=2068187884
> リダイレクト処理の修正

- src/package-lock.json
- src/package.json
> [fix] セキュリティアラートへの対応

- src/src/App.vue
- src/src/components/molecules/ProfilePageMenu.vue
- src/src/components/organisms/AccountSettings.vue
- src/src/components/organisms/Header.vue
- src/src/components/organisms/HeaderMenu.vue
- src/src/components/pages/Profile.vue
- src/src/router.ts
[fix] カテゴリのタグを押したら一番上に遷移してしまう問題の解消
[fix] ログイン後にプロフィールではなくquestionsにborder-bottomがついてしまう問題の解消
[fix] 設定ページでリロードするとエラーになるバグ修正
[fix] ヘッダーのリファクタリング
> 画面遷移時のバグ修正など

- src/package-lock.json
- src/package.json
- src/src/App.vue
- src/src/auth/authService.ts
- src/src/components/molecules/CategoryLabels.vue
- src/src/components/organisms/Impressions.vue
- src/src/components/organisms/ModalForm.vue
- src/src/components/organisms/ModalShare.vue
- src/src/components/organisms/Questions.vue
- src/src/vue-shim.d.ts
[fix] クリップボードへのコピーをできるようにするライブラリを追加
[fix] URLコピーができるように機能を追加
[fix] モーダルを表示したときに背景を固定
[fix] 認証画面へ遷移するように修正
[fix] 投稿フォームの文字制限を表示＆背景固定
[fix] カテゴリが横スクロールする場合にデザインが崩れるため修正
> リンクコピー&モーダル背景固定&フォームの文字制限

- src/src/components/organisms/Impressions.vue
> [fix] レコメンドの表示箇所を微修正

- src/public/index.html
> add static meta tag

- src/package-lock.json
- src/package.json
- src/server.js
- src/src/main.ts
> [OGP対応] Twiter Bot対応

- src/server.js
> add slackbot to isBot function

- src/public/index.html
- src/src/App.vue
- src/src/components/organisms/ModalShare.vue
> Fix ogp meta tags

- src/src/components/molecules/CategoryLabels.vue
- src/src/components/molecules/QAContent.vue
- src/src/components/molecules/ReactionIconGroup.vue
- src/src/components/organisms/Questions.vue
- src/src/components/pages/Profile.vue
- src/src/router.ts
[fix] 質問カテゴリーを変更したときページ上部へ移動させる
[fix] 個別回答のユーザーアイコンを押したらプロフィールへ遷移するように修正
[fix] カテゴリラベルの色を変更。今選択しているカテゴリに吹き出しを付けるように修正
> 質問カテゴリーを変更したときページ上部へ移動させる&個別回答のユーザーアイコンを押したらプロフィールへ遷移する&カテゴリラベルの色を変更

- src/src/components/organisms/Individual.vue
> [fix] 個別ページでTweetを促す画像とリンクを貼った

- src/src/components/pages/PrivacyTemplate.vue
> [fix] 文言が違ったので修正
